export const masterTechStack = [
  "AI Ticket Categorization",
  "Android App",
  "Bootstrap 5",
  "Chart.js",
  "Cloudflare D1 & R2",
  "Cloudflare Workers",
  "CodeIgniter 3",
  "Docker",
  "Express.js",
  "FastAPI",
  "Filament PHP",
  "Flutter",
  "FullCalendar",
  "GCP Cloud",
  "GitHub API",
  "Go 1.25+",
  "Hono",
  "Inertia.js",
  "JavaScript",
  "Jetpack Compose",
  "Kotlin",
  "Laravel",
  "Laravel 13",
  "Leaflet GIS",
  "Livewire 4",
  "Lucide Icons",
  "MDX",
  "MySQL",
  "Next.js",
  "Next.js 15",
  "Node.js",
  "NumPy",
  "OAuth2",
  "Pandas",
  "PHP",
  "PostgreSQL",
  "Proxmox VE",
  "Python",
  "Python AI Service",
  "R Shiny",
  "React",
  "React 19",
  "Retrieval-Augmented Generation (RAG)",
  "Room Database",
  "SEO Optimization",
  "SQLite",
  "SSO Keycloak",
  "Streamlit",
  "Tailwind CSS",
  "Tailwind CSS v4",
  "Telegram MTProto",
  "TypeScript",
  "UI/UX Figma",
  "Vite",
  "Wails v2"
];

export const masterCategories = [
  "Sistem Web",
  "Aplikasi Web",
  "Sistem Enterprise",
  "Data & Analytics",
  "Aplikasi Mobile",
  "Mobile & API",
  "Aplikasi Desktop",
  "Microservices & DevOps",
  "Riset & Machine Learning",
  "Redesain UI/UX"
];
