export const masterTechStack = [
  "AI Ticket Categorization",
  "Android",
  "Android App",
  "Bootstrap",
  "Bootstrap 5",
  "Chart.js",
  "Cloudflare D1 & R2",
  "Cloudflare Workers",
  "CodeIgniter 3",
  "Coroutines",
  "CSS3",
  "Data Visualization",
  "Desktop App",
  "Docker",
  "Express.js",
  "FastAPI",
  "Filament PHP",
  "Flutter",
  "FPDF",
  "FullCalendar",
  "GCP Cloud",
  "GitHub API",
  "Go 1.25+",
  "Hono",
  "HTML/CSS",
  "HTML5",
  "Inertia.js",
  "JavaScript",
  "Jetpack Compose",
  "jQuery",
  "Keycloak",
  "Kotlin",
  "Laravel",
  "Laravel 13",
  "Leaflet GIS",
  "Livewire",
  "Livewire 4",
  "Lucide Icons",
  "Material Design 3",
  "Matplotlib",
  "MDX",
  "MTProto GramJS",
  "Multinomial Logistic Regression",
  "MySQL",
  "Next.js",
  "Next.js 15",
  "Node.js",
  "NumPy",
  "OAuth2",
  "Pandas",
  "PHP",
  "PostgreSQL",
  "Postman",
  "Proxmox VE",
  "Python",
  "Python AI Service",
  "R",
  "R Shiny",
  "React",
  "React 19",
  "React (Inertia.js)",
  "REST API",
  "Retrieval-Augmented Generation (RAG)",
  "Room Database",
  "RSS Reader",
  "SEO Optimization",
  "Shiny Dashboard",
  "Spatie Permission",
  "SQLite",
  "SSO Integration",
  "SSO Keycloak",
  "Streamlit",
  "Tailwind CSS",
  "Tailwind CSS v4",
  "Telegram MTProto",
  "TypeScript",
  "UI/UX Figma",
  "Vite",
  "Wails v2",
  "WhatsApp Bot API"
];

export const masterCategories = [
  "Sistem Web",
  "Aplikasi Web",
  "Sistem Enterprise",
  "Data & Analytics",
  "Aplikasi Mobile",
  "Mobile & API",
  "Aplikasi Desktop",
  "Microservices & DevOps",
  "Riset & Machine Learning",
  "Redesain UI/UX"
];
